import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/header/NavBar";
import ServiceWorkerRegistration from "@/components/ServiceWorkerRegistration";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
          if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }
        `,
          }}
        />
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "nvwqp3qoey");
            `,
          }}
        />
      </head>
      <body
        className={`
          ${inter.className}
          flex min-h-screen flex-col
        `}
      >
        <div
          className={`
            grid-background-md
            md:hidden
          `}
        />
        <div
          className={`
            grid-background hidden
            md:block
          `}
        />
        <NavBar />
        <main
          className={`
            grow
            md:pt-4
          `}
        >
          <div
            className={`
              md:shadow-3xl md:rounded-xl md:py-4
              container mx-auto max-w-5xl border-2 border-slate-200 bg-slate-50 p-2
              dark:border-slate-700 dark:bg-slate-900
            `}
          >
            {children}
          </div>
        </main>
        <Toaster />
        <ServiceWorkerRegistration />
        <Footer />
      </body>
    </html>
  );
}
